### ISSUE TITLE
Add jsonfield version specification in requirements

### ISSUE THREAD

**Issue by Saumya-Mishra9129** [FusionIIIT/Fusion#162]
Error while running on local server-
`Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Saumya\Downloads\Fusion\FusionIIIT\applications\globals\views.py", line 712, in dashboard
    return render(request, "dashboard/dashboard.html", context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\test\utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\test\utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\loader_tags.py", line 216, in render
    return template.render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\test\utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = self.nodelist.render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\template\defaulttags.py", line 173, in render
    len_values = len(values)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\db\models\query.py", line 232, in __len__
    self._fetch_all()
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\db\models\query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\db\models\query.py", line 62, in __iter__
    for row in compiler.results_iter(results):
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\db\models\sql\compiler.py", line 847, in results_iter
    row = self.apply_converters(row, converters)
  File "C:\Users\Saumya\Downloads\Fusion\env\lib\site-packages\django\db\models\sql\compiler.py", line 832, in apply_converters
    value = converter(value, expression, self.connection, self.query.context)
TypeError: from_db_value() takes 4 positional arguments but 5 were given`

Alternative use  `pip install jsonfield==2.1.1`
Or add `jsonfield == 2.1.1` in requirements.txt

**Comment by salarx** [comment]
Can you please provide the steps to reproduce this issue? Is the issue associated with particular user type or every user?

**Comment by salarx** [comment]
Closing issue due to inactivity. Reopen if it occurs.
